### ISSUE TITLE
Tech: add the linter to the pre commit hook

### ISSUE THREAD

**Issue by idodav** [sharkio-dev/sharkio#145] opened 2023-07-23 16:58 UTC

**Comment by SID262000** [comment] 2023-07-24 09:30
I can't start working on this issue as long as there exists even 1 Typescript-based syntax error reported from the linter as discussed with @nkotzrenko, warnings are acceptable.
Once all the errors are fixed, I can proceed with adding a pre-commit hook & successfully integrating it as part of the GitHub Actions

**Comment by SID262000** [comment] 2023-07-24 10:20
Looks like there are no more errors, we have 33 Warnings only.
@idodav Please assign this Issue to me, will start the work

**Comment by idodav** [comment] 2023-07-24 10:32
Assigned!

**Comment by SID262000** [comment] 2023-07-29 10:31
It seems that the issue is more significant than what I initially expected. One of the primary reasons behind it could be that the development work began without implementing pre-commit hooks to guarantee that only top-notch code is pushed to the primary repository. As I continue to investigate the matter and devise a comprehensive solution, I will keep you informed through this thread.

**Comment by SID262000** [comment] 2023-07-29 10:31
@idodav Feel free to discard both the Pull Requests associated with this Issue

**Comment by SID262000** [comment] 2023-07-31 18:11
Since the `.git ` folder is excluded and is not tracked by the Git system, we have 2 proposed methods to go forward with the integration of the pre-commit hook:

1. Share the pre-commit hook as an additional script and ask everyone on the Team to integrate it into their local system.
2. Create a pre-commit hook outside of the `.git `folder, maybe `_githooks` to make sure it's tracked by the Git system followed by creating a symbolic link from the `.git` section to ensure always the latest script gets used.

One major drawback of the initial approach is the need for manual sharing of the script whenever updates are made.

@idodav Your valuable suggestions will be really helpful, Thanks

**Comment by idodav** [comment] 2023-08-12 11:28
@SID262000 Is this resolved? Did you make any progress?

**Comment by SID262000** [comment] 2023-08-13 08:26
> Since the `.git ` folder is excluded and is not tracked by the Git system, we have 2 proposed methods to go forward with the integration of the pre-commit hook:
> 
> 1. Share the pre-commit hook as an additional script and ask everyone on the Team to integrate it into their local system.
> 2. Create a pre-commit hook outside of the `.git `folder, maybe `_githooks` to make sure it's tracked by the Git system followed by creating a symbolic link from the `.git` section to ensure always the latest script gets used.
> 
> One major drawback of the initial approach is the need for manual sharing of the script whenever updates are made.
> 
> @idodav Your valuable suggestions will be really helpful, Thanks
> 
> 

I had a blocker here, updated in the preceding thread.

**Closed** 2023-11-19 10:01 UTC
